### ISSUE TITLE
Distinguishing whether the esc key is pressed or the arrow key pressed

### ISSUE THREAD

**Issue by theHapalua** [theHapalua/Pinov#1]
in runScreen function in scrctrl.h, program gets arrow keys from user but it can't get the difference between esc and arrow keys. If user presses esc+[+A, code gets it as upper arrow but it shouldn't do.

**Comment by M-Enes** [comment]
It works like that because esc+[+A input is equivalent to up arrow. That's same for all similar keystrokes. To change this, maybe we can add some code which waits e.g. 50 msces for notice difference between esc+[+A and just up arrow.

**Comment by theHapalua** [comment]
Then another problem occurs. User presses esc in order to exit from insert mode but s/he has to press another key to let computer measure the time between two keys. Can the problem be solved with threads?

**Comment by M-Enes** [comment]
I think problem can solved by using threads. However, it might be make our code much more complicated. We should look for another solution.

**Comment by M-Enes** [comment]
It seems your commit solves the problem. Great! It is not an issue anymore.
